### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by kmckee** [julien/generator-phaser#34]
I think it would be really helpful if the documentation included a reference to a project that used this generator, so that people that are newer to Phaser (myself)could dig into the code.

**Does anyone have any projects that they feel would be a good example based on the project structure that this generator creates?**

I'm overwhelmed by possibilities at this point and would like to just base the structure of my project similar to what someone else, with more experience, has done.  Thanks :)

**Comment by GlennGeenen** [comment]
This generator is pretty useless if you don't know phaser, so the first step is learning the basics of phaser, for this you should check out all Phaser Examples: http://phaser.io/examples. Phaser has amazing documentation and examples, they should provide everything you need.

I have a Flappybird example that uses this generator (old version): https://github.com/GlennGeenen/FlappyBird

**Comment by Murazaki** [comment]
I'm sorry but this generator clearly lacks extended examples.

I can't figure out how you're supposed to load classes inheriting Phaser.Sprite. You can't create them from the state constructor because you don't have the game object yet, and you seem to need to call preload() and create() by yourself. Also calling add.existing(ObjectInheritingSprite) doesn't seem to work for me.

**Comment by julien** [comment]
Hi @Murazaki,

Don't be sorry, no offense taken here ;)

I don't plan to add Phaser examples, since they already do a great job on the Phaser website and that people are more likely to search on there than here.

I tried to create a class extending `Phaser.Sprite` and here's what I did.

- I used the generator to get the "boilerplate" code ready.

- Created a new directory called `sprites` under the `src` directory.

- Created a new file called `test.js` in the `src/sprites` directory with the following content:

  ```javascript
  class Test extends Phaser.Sprite{
    constructor(game, x, y, key, frame) {
      super(game, x, y, key, frame);
    }
  }
  export default Test;
  ```

- I edited  `src/states/game.js` and added 

  ```javascript
  import Test from '../sprites/test';
  ```

  At the top of the file (i.e. the first line)

  I also added this in the `create` function:

  ```javascript
  this.test = new Test(
    this.game, 
    this.game.width * 0.5 - 64, 
    this.game.height * 0.5 - 64, 
    'test-sprite',  
    0);
  this.world.add(this.test);
  ```

- I edited `src/states/boot.js` and added this line in the `preload` function:

    ```javascript
    this.load.image('test-sprite', 'assets/test-sprite.png'); 
    // Note that you'll need an image called "test-sprite.png" in your assets folder for this to work
    ```

- When I "run" the example and get to the "game" state, I can see my sprite on the screen


I attached a [.zip archive](https://github.com/julien/generator-phaser/files/545900/test.zip) with the "whole" changes if you're interested.

**Comment by Murazaki** [comment]
I see.

While you were responding, I managed to make my code work with little changes on your structure.

See, what's bothering me the most is the preload function you add in classes inheriting Sprites. They can't be used because you need to create the Sprites in order to call them... So I made them static (which seems logical to me).

For example, here is the code of my GameScene Background Image :


````Javascript
const gamescenekey = 'gamescene';

//Documentation for Phaser's (2.5.0) states:: phaser.io/docs/2.5.0/Phaser.State.html
class GameScene extends Phaser.Image {

  //initialization code in the constructor
  constructor(game, x, y) {
    console.log('constructing GameScene');
    super(game, x, y, gamescenekey);
  }

  //Load operations (uses Loader), method called first
  static preload(game) {
    console.log('preloading GameScene');

    game.load.image(gamescenekey,'assets/sprites/fond_grotte.jpg');
  }

  create() {
    console.log('creating GameScene');
    this.anchor.set(0);

    this.width = this.game.width;
    this.height = this.game.height;
  }
}
````

And here's how I call it in my Game state :

````Javascript
import GameScene from '../prefabs/Scenes/gamescene';

class Game extends Phaser.State {

  constructor(game) {
    super();
  }

  preload() {
    // Like this, I can preload a sprite even if it doesn't exists,
    // and it will be preloaded only once
    GameScene.preload(this.game);
  }

  create() {
    this._gameScene = new GameScene(this.game, 0, 0);
    this.add.existing(this._gameScene);
    this._gameScene.create();

    this.input.onDown.add(this.endGame, this);
  }

  update() {

  }

  endGame() {
    this.game.state.start('gameover');
  }

}

export default Game;
````

What do you think about this ?

**Comment by julien** [comment]
Looks OK to me
